version: "3.8"

services:

  server:
    container_name: tyranno-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: tyranno-db
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - ./server/.env.sample
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

  adminer:
    container_name: tyranno-adminer
    image: adminer:latest
    ports:
      - 8888:8080
    depends_on:
      db:
        condition: service_healthy
