version: "3"

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - ./server/.env.sample

  adminer:
    image: adminer:latest
    ports:
      - 8888:8080
    depends_on:
      - db